version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/android:api-28-node
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
jobs:
  build:

    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: gradlew build
          command: ./gradlew build
      - run:
          name: gradlew test
          command: ./gradlew test