version: 2.1

orbs:
  android: circleci/android@0.2.0
  environment:
    JVM_OPTS: -Xmx2048m
    GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: gradlew build
          command: ./gradlew clean assemble
      - run:
          name: gradlew test
          command: ./gradlew test