version: 2.1

orbs:
  android: circleci/android@0.2.0
  environment:
    JVM_OPTS: -Xmx4g

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: gradlew build
          command: ./gradlew build
      - run:
          name: gradlew test
          command: ./gradlew test